# Generated by Django 3.2.13 on 2022-06-21 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='제목')),
                ('thumbnail', models.FileField(upload_to='product/', verbose_name='썸네일')),
                ('description', models.TextField(verbose_name='설명')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('exposure_start_date', models.DateField(verbose_name='노출 시작 일자')),
                ('exposure_end_date', models.DateField(verbose_name='노출 종료 일자')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
        ),
    ]
