# Generated by Django 3.2.13 on 2022-06-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='exposure_end_date',
            field=models.DateField(verbose_name='노출 종료 일자'),
        ),
    ]
